### PR TITLE
Validate subaccount and memo with 32 bytes

### PR DESCRIPTION
**Pull request by tomijaga**
I was going through your ICRC1 implementation as a reference for the one I was creating for Motoko.

I saw that this issue https://github.com/demergent-labs/ICRC-1/issues/3 and made a PR to fix it.

### CODE REVIEW

**Comment by lastmjs** [comment]
Hey thanks, I believe there's more to fix than just those checks.

**Comment by lastmjs** [comment]
I think this also needs to be changed: https://github.com/demergent-labs/ICRC-1/blob/main/src/account.ts#L36

To fully complete this feature, I would like to know if you manually tested subaccounts, and we should probably add some tests to ensure this is working properly.

If you aren't interested in all of that work (since you were just browsing for Motoko) just let us know :) We can handle it from here if you'd like.

**Comment by tomijaga** [comment]
Hey @lastmjs, I didn't test the subaccounts, I just looked at the [ledger docs](https://docs.rs/ic-ledger-types/latest/ic_ledger_types/struct.Subaccount.html) to make sure they were 32 bytes.

Thanks for bringing the remaining issues to my attention. I will fix them and update the PR.
Also nice testing framework at `azle`. I think writing tests will be a good opportunity to get familiar with it.

**Comment by tomijaga** [comment]
Hey, I changed the subaccount key from `nat32` to a 64-length `hex string`. 
I wasn't able to get install `azle` and get the tests running on my mac.
So I guess you can take it from here 🙂

**Pull request closed without merging**
